### ISSUE TITLE
syslog now rsyslog? messages log not updating

### ISSUE THREAD

**Issue by gregarios** [plesk/centos2alma#116]
**Describe the bug**
the /var/log/messages log stopped updating and has a zero filesize for the last few days.

After updating to AlmaLinux from CentOS, is there a difference in logging?

My settings are looking for:
`/var/run/syslogd.pid`

but all that exists is:
`/var/run/rsyslogd.pid`

```
cat /etc/logrotate.d/* | grep syslog
/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
/usr/bin/systemctl -s HUP kill rsyslog.service >/dev/null 2>&1 || true

cat /var/run/syslogd.pid
cat: /var/run/syslogd.pid: No such file or directory

cat /etc/logrotate.d/syslog
/var/log/cron
/var/log/messages
/var/log/secure
/var/log/spooler
{
    missingok
    sharedscripts
    postrotate
	/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}

```

This may be something needing change on conversion?
Should any kills be done to rsyslogd.pid instead of syslogd.pid now?

**Comment by SandakovMM** [comment]
Hay @gregarios,
> After updating to AlmaLinux from CentOS, is there a difference in logging?

I believe AlmaLinux uses rsyslod by default. So yes, likely you are right about moving to different logging system. 

Regarding logrotate configuration problem. When installing AlmaLinux from scratch, the proper configuration file for log rotation should be in place. However, when we converting from CentOS 7 Elevate is unable to handle this situation because the file is marked as a configuration file for syslog package, preventing it from changing the file during the installation of new packages.
I will make the necessary changes on the centos2alma side to address this issue. 

Additionally, I have attached the logrotate file from my AlmaLinux 8 instance, which you can try to use on your instance. It should be fine with rsyslog. You can find the file here: [syslog.txt](https://github.com/plesk/centos2alma/files/11951641/syslog.txt)

To ensure that your messages file is updated with new messaged, you should restart your rsyslog using systemd. For example by this command:
```shell
systemctl restart rsyslog
```
Please note that the logrotate file should be fixed regardless. Otherwise, the problem will reoccur after the next rotation.

**Comment by SandakovMM** [comment]
I have merged pull request #117 to resolve the logrotate issue for syslog after the conversion. It should be working fine now.

Additionally, I noticed that the build based on GitHub Actions is currently using the wrong interpreter, which won't work on a typical CentOS 7 server. If you require the actual centos2alma build, please reach out to me, and I will share it with you.

Thank you.

**Comment by gregarios** [comment]
Do I keep all the settings files in the **/etc/logrotate.d** directory, or do I need to move them all to the **/etc/rsyslog.d** directory?

Currently:
`ll /etc/logrotate.d/
total 96K
-rw-r--r--. 1 root root    91 Apr 18  2022 bootlog
-rw-r--r--. 1 root root   130 Apr  1 17:29 btmp
-rw-r--r--. 1 root root   160 Dec 16  2021 chrony
-rw-r--r--. 1 root root    88 Apr 12  2021 dnf
-rw-r--r--. 1 root root   400 May 12 06:12 fail2ban
-rw-r--r--. 1 root root    93 Apr 18  2022 firewalld
-rw-r--r--. 1 root root   202 Jun 26 23:18 httpd
-rw-r--r--. 1 root root   162 May 30 12:06 kvm_stat
-rw-r--r--. 1 root root  1.9K Jun  5 17:10 mariadb
-rw-r-----. 1 root named  514 Apr  3 01:12 named
-rw-r--r--. 1 root root    94 Jun  2 10:30 nginx
-rw-r--r--. 1 root root   195 Jun 18 22:58 plesk
-rw-r--r--. 1 root root   221 Jun  9 00:38 plesk-php80
-rw-r--r--. 1 root root   221 Jun  9 00:23 plesk-php82
-rw-r--r--. 1 root root   136 Feb 25  2020 ppp
-rw-r--r--. 1 root root    68 Apr 18  2022 sa-update
-rw-r--r--. 1 root root   149 May 23 02:48 sw-cp-server
-rw-r--r--. 1 root root   114 Jan  1  1990 sw-engine
-rw-r--r--. 1 root root   207 Jun 26 23:17 syslog
-rw-r--r--. 1 root root   226 Mar 31 17:41 syslog.rpmnew
-rw-r--r--. 1 root root   100 Apr 18  2022 wpa_supplicant
-rw-r--r--. 1 root root  2.0K Jul  4 23:27 wp-toolkit-action-logs
-rw-r--r--. 1 root root   145 Feb 19  2018 wtmp
`

**Comment by SandakovMM** [comment]
The directory is right, because the syslog file is actually configuration of logrotate.

**Comment by gregarios** [comment]
Thank you. So far so good. :-)
