### ISSUE TITLE
wrong PHP-Version in crons / plesk scheduled tasks

### ISSUE THREAD

**Issue by m-witt** [plesk/centos2alma#146]
**Describe the bug**
After the successful upgrade to Alma8 usercrons are still trying to use old/removed php-versions.
Crontabs are not updated.

**Steps to reproduce**
1. Create "scheduled task" with php script execution and any php-version which will get removed (for example php 5.6) in plesk
-> will create : 
```[root@abc123 httpdocs]# crontab  -l -u abc123
MAILTO=""
MAILTO="marcel@abc123.tld"
SHELL="/bin/sh"
*/5     *       *       *       *       (/opt/plesk/php/5.6/bin/php -f 'httpdocs/test.php')  > /dev/null
```
2. remove old php-versions `yum remove -y plesk-php5* plesk-php70* plesk-php71*`
 -> at this point plesk will select the next available php-version in the "scheduled tasks"-mask. Crontabs will remain unchanged

3. Start conversion `./centos2alma`
4. check crontabs after upgrade again

**Possible solution(s)**
- RPM Post-Script which rewrites usercrons to available versions ?
- Handle this within the upgrade/conversion process ?
- Any command which we can manually execute after upgrade to update all tasks ?

**Comment by SandakovMM** [comment]
Hello,
apologize for the delay

I believe that the problem can be effectively resolved from the Plesk side, so let me investigate what actions we can take within the Plesk to address this.

Regarding a workaround. Unfortunately, I can't find a way to change the PHP interpreter in Plesk for a task through the command line interface. Since that scheduled tasks are stored in the Plesk database we should change the interpreter exactly in Plesk. Therefore, it seems that the only suitable approach for making this change is through the web-based UI.

**Comment by SandakovMM** [comment]
I've talked about it with the rest of the team, and it seems like the solution could take a significant amount of time. Therefore, I cannot provide an estimate for when the PHP interpreter for a cron job will switch automatically in Plesk.
I will add a checker to ensure that there are no cron jobs connected to outdated PHP before the conversion.

**Comment by SandakovMM** [comment]
I have added a pre-conversion check action to detect if any cronjobs are using an outdated version of PHP as a handler. Related PR is #155
