### ISSUE TITLE
Sometimes the temp FS is still too small

### ISSUE THREAD

**Issue by ManfredLan** [plesk/centos2alma#166]
With 1.2.3 I hit sometimes the problem, that the temp FS was too small, so I had to use
"export LEAPP_OVL_SIZE=6000" to increase it to a sufficient size.

In addition this caused the upgrade to fail during the first run.
When trying to use "centos2alma --finish" the script asked to run "dnf update -y" again, which caused the installation of of a newer LEAPP package which in turn installed MariaDB 11.1 again, which was addressen in #158 and #159 respectively.

I lost the logs sadly.

This is more of a FYI.

**Comment by SandakovMM** [comment]
The issue with the pre-checker has been resolved in #167. If you have already installed Leapp and are unable to start centos2alma because it is being detected as outdated, you should disable the elevate repository by using the command `/usr/bin/yum-config-manager --disable elevate`.
I believe we should disable the repository just to ensure that there is no possibility of accidentally updating Leapp to the latest version by running `yum update`.

Regarding LEAPP_OVL_SIZE it's a grate insight, thank you. Likely we could use it.

**Comment by SandakovMM** [comment]
It seems that the issue with the filesystem being too small has been [resolved on the Leapp side, and the LEAPP_OVL_SIZE is no longer relevant](https://github.com/SandakovMM/leapp-repository/commit/d074926c75eebc56ca640e7367638bbeaa1b61a2).
We are going to move to the new version of leapp. Hopefully soon.
