### ISSUE TITLE
AWStats configurations for domains left unchanged after the conversion

### ISSUE THREAD

**Issue by SandakovMM** [plesk/centos2alma#185]
**Description**
Plesk domains that use awstats have custom configuration files stored in the `/usr/local/psa/etc/awstats/` directory. These files are created using the `/etc/awstats/awstats.model.conf` file from the awstats package. After the conversion, we need to regenerate these files as the template has been updated.
Additionally, if the new template is stored as rpmnew, we need to replace it with the original `/etc/awstats/awstats.model.conf` file.

**Comment by SandakovMM** [comment]
The problem should be solved by #189

**Comment by Bitpalast** [comment]
Not yet fixed in latest centos2alma script. Result in /etc/awstats directory:

total 336
drwxr-xr-x.  2 root root  4096 Mar  5 12:02 .
drwxr-xr-x. 98 root root 12288 Mar  5 12:02 ..
-rw-r--r--.  1 root root 64519 Mar  5 12:02 awstats.ems.conf
-rw-r--r--.  1 root root 64523 Mar  5 12:02 awstats.localhost.localdomain.conf
-rw-r--r--.  1 root root 64542 Mar  5 12:02 awstats.localhost.localdomain.conf.rpmsave
-rw-r--r--.  1 root root 64523 Mar  5 12:02 awstats.model.conf
-rw-r--r--.  1 root root 64692 Mar  5 12:02 awstats.model.conf.rpmsave

**Comment by SandakovMM** [comment]
Hmm, there is no .rpmnew files in the /etc/awstats as far as I could see. We store the old files in the .rpmsave files, which seems to be the expected behavior to me

**Comment by Bitpalast** [comment]
You are probably right. I checked this again on pre-conversion servers and found that

-rw-r--r--.   1 root root 63602 Mar 13 10:06 awstats.localhost.localdomain.conf
-rw-r--r--.   1 root root 64542 Mar 13 10:06 awstats.localhost.localdomain.conf.rpmnew
-rw-r--r--.   1 root root 63752 Mar 13 10:06 awstats.model.conf
-rw-r--r--.   1 root root 64542 Mar 13 10:06 awstats.model.conf.rpmnew
-rw-r--r--.   1 root root 63583 Mar 13 10:06 awstats.selke.conf

is obviously a status from before conversion. So the underlying issue with outdated awstats.conf files exists in Plesk in general. It now became visible through the centos2alma conversion as it had an effect when the software is updated. 

So o.k., I agree that I was just mislead when checking a post-conversion status.
