### ISSUE TITLE
Early abort with "codec can't encode character"

### ISSUE THREAD

**Issue by abien** [plesk/centos2alma#228]
At the very start the script aborts with
```
2024-04-02 22:29:14,689 - ERROR - 'ascii' codec can't encode character '\u201c' in position 424: ordinal not in range(128)
2024-04-02 22:29:14,690 - ERROR - Please fix noted problems before proceed the conversion
```

[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/14843585/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment]
Could you please call the script in verbose mode (`--verbose`) again and provide /var/log/plesk/centos2alma.log

**Comment by nilsringersma** [comment]
Hi @SandakovMM , I saw the OP did not response however I'm getting the same error. Below is the execution in verbose mode:

```
./centos2alma --verbose
Doing preparation checks...
Preparation checks failed: 'ascii' codec can't encode character '\u201c' in position 330: ordinal not in range(128)
Traceback (most recent call last):
  File "/root/centos2alma/pleskdistup/main.py", line 109, in required_conditions_satisfied
    writer.write(check)
  File "/root/centos2alma/pleskdistup/common/src/writers.py", line 22, in write
    sys.stdout.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 330: ordinal not in range(128)

Conversion can't be performed due to the problems noted above
```

**Comment by SandakovMM** [comment]
Hi @nilsringersma,
Could you please provide the /var/log/plesk/centos2alma.log file?

**Comment by SandakovMM** [comment]
Ok, thank you. I will fix the problem with non-ascii symbol output into a logfile.

**Comment by abien** [comment]
> Could you please call the script in verbose mode (`--verbose`) again and provide /var/log/plesk/centos2alma.log
[centos2alma.log](https://github.com/plesk/centos2alma/files/15254249/centos2alma.log)

**Comment by SandakovMM** [comment]
Hello,
I spent some time attempting to replicate the issue on my end and managed to do so only when the values of `LC_ALL` and `LANG` were changed to `C`. Could you please provide the current values of these environment variables from your server?
As a temporary fix, I recommend invoking centos2alma with the specified variables: `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 ./cetos2alma...`

**Comment by nilsringersma** [comment]
Thanks @SandakovMM for me `LC_ALL` is empty and `LANG` is set to `C.UTF-8`.

```
15:00:19 [root@xxx ~]# echo $LC_ALL

15:00:25 [root@xxx ~]# echo $LANG
C.UTF-8
```

From now on I will invoke the script with the specified variables.

**Comment by SandakovMM** [comment]
Thank you @nilsringersma, I can see `$LANG=C.UTF-8` triggers the problem as well. :+1:

**Comment by SandakovMM** [comment]
Ok, we spend some time to find a solution to the problem, and we believe it is satisfactory. The solution provided as part of [centos2alma v1.3.1](https://github.com/plesk/centos2alma/releases/tag/v1.3.1)

To begin with, we made the decision not to change the default encoding because we cannot guarantee the outcome of the conversion on systems with inconsistent locales. This means that although it may work for one wrongly encoded configuration file, it could cause issues with other files. Additionaly the inconsistancy could be unexpected by leapp, not only by centos2alma itself.
As a default solution, we have implemented a different method for handling encoding errors when writing logs. In the new centos2alma version, you will encounter a similar error, but it should specify which pre-check has failed, allowing you to identify the problematic file.

We have also introduced a `--locale` option for the tool, which enables you to configure the locale that the script will use. However, we strongly advise investigating the root cause of the problem, such as identifying the specific file or installed package causing the issue. In the past, encoding problems have resulted in failures in the temporary OS used by leapp to reinstall packages, and this has led to instances becoming stuck. Therefore, caution is advised when using the `--locale` option.

Furthermore, it would be greatly appreciated if you could provide the results of your investigation into your encoding problems. This will enable us to add a pre-checker to identify local inconsistencies before commencing with the conversion.

**Comment by nilsringersma** [comment]
Great @SandakovMM, thank you for the addition in the new release. I will keep you updated on any encoding problems we encounter.

So far, I’ve been running the solution `LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 ./centos2alma` on approximately 245 hosts. About 85% of the hosts were successfully upgraded. The remaining hosts usually failed the pre-checks because GRUB was not installed. You saved me a lot of time; many thanks for that 🙏.

If you’re interested, I have some further feedback that is not directly related to this issue:

1.	I also added a check to ensure the host has at least 2GB of RAM. I had over seven hosts fail with only 1GB of RAM and get stuck during the upgrade phase. When checking the output through the serial port, it showed the OOM killer had terminated processes, causing the upgrade to get stuck. If you want, I can open a new issue for it. Personally, it’s not a problem for me as I don’t prefer running Plesk on 1GB machines anyway. So now I upgrade the available memory pre-conversion.
2.	I had a couple of hosts where mailboxes were used, and users could not log in to the IMAP server after the conversion. The error was Failed to initialize SSL server context: Can't load DH parameters, as described in [this Plesk support article](https://support.plesk.com/hc/en-us/articles/12377016572439-Unable-to-log-in-to-Roundcube-webmail-or-using-email-client-on-Plesk-server-Can-t-load-DH-parameters-dh-key-too-small). As a solution, I now run `plesk sbin sslmng --service dovecot --strong-dh --dhparams-size=2048` post-conversion.

Thanks again for making this conversion script available 😄.

**Comment by SandakovMM** [comment]
@nilsringersma, thank you for the feedback! It is greatly appreciated and helps us to improve the tool
