### ISSUE TITLE
Issue with 1.2.4 and Kernel Image

### ISSUE THREAD

**Issue by kiwigringo** [plesk/centos2alma#240]
There are several issues with upgrades, some that I managed to solve, one that I couldn't resolve.

The server had previously had PostgreSQL installed, but was no longer being used, so I uninstalled this from the Plesk component and upgrades UI, however centos2alma complained that it could not find PostgreSQL even though it was not installed.

Reinstalling and using the forced upgrade option resolved this, since postgreSQL wasn't being used in any case, there was no risk of data loss.

The next issue was with Maria DB. The Version installed is 10.5.x which is not the default with CentOS 7.

First there was an error stating there was no file /etc/yum.repos.d/mariadb.repo and no repository could be found.
The actual file was named /etc/yum.repos.d/MariaDB10.repo 

I attempted to rename this file, and this resulted in the process proceeding for several more steps, and appeared to successfully upgrade MariaDB.

The script failed with an error "Message: Cannot find any installed kernel signed by Red Hat."

Repositories configured on system in yum.repos.d are as shown:

![image](https://github.com/plesk/centos2alma/assets/5873116/0ec1f79e-ccf0-495e-94ce-998d0568d26c)

In CentOS-x86_64-kernel.repo:

[centos-kernel]
name=CentOS LTS Kernels for $basearch
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=kernel&infra=$infra
#baseurl=http://mirror.centos.org/altarch/7/kernel/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

[centos-kernel-experimental]
name=CentOS Experimental Kernels for $basearch
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=experimental&infra=$infra
#baseurl=http://mirror.centos.org/altarch/7/experimental/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

[centos2alma_feedback.zip](https://github.com/plesk/centos2alma/files/15039615/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment]
Hello @kiwigringo,
I will fix the problems regarding the postgresql and mysql repo file issues in the first patch release after 1.3.0. Thank you for bringing these issues to my attention

> The script failed with an error "Message: Cannot find any installed kernel signed by Red Hat."

The error is due to the use of a kernel from the xen repository, as seen in the snippet below:
```
...
kbd-misc.noarch               1.15.5-16.el7_9                @updates           
kernel.x86_64                 3.18.44-20.el7                 @centos-virt-xen   
kernel.x86_64                 4.9.215-36.el7                 @centos-virt-xen-46
kernel-headers.x86_64         4.9.215-36.el7                 @centos-virt-xen-46
kexec-tools.x86_64            2.0.15-51.el7_9.3              @updates           
...
```
The xen repository related file /etc/yum.repo.d/CentOS-Xen.repo:
```
# CentOS-Xen.repo
#
# Please see http://wiki.centos.org/QaWiki/Xen4 for more 
# information

[centos-virt-xen-46]
name=CentOS-$releasever - xen
baseurl=http://mirror.centos.org/centos/$releasever/virt/$basearch/xen-48
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Virtualization

[centos-virt-xen-46-testing]
name=CentOS-$releasever - xen - testing
baseurl=http://buildlogs.centos.org/centos/$releasever/virt/$basearch/xen-48
gpgcheck=0
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Virtualization
```
It appears that this kernel is not signed by Red Hat, causing the restriction about the signature from the "elevate" side. We utilize the "elivate" tool to convert the host (IIRC the tool provided by RedHat). Unfortunately, there is nothing we can do about this at the moment.

In theory we could add a similar check in the pre-checking stage to prevent conversion before stopping plesk services. After that, we may try to exclude this check on the "elivate" side somehow to allow the conversion for specific kernels (for example xen kernels)
For now, I suggest installing the default CentOS 7 kernel to proceed with the conversion.

**Comment by SandakovMM** [comment]
The postgresql related problem should be fixed by #245

**Comment by SandakovMM** [comment]
I've added a restriction for conversion when there is no Red Hat kernel installed, so conversion will be prevented in this case - #249.
I will try to fix the problem with mariadb10.repo file as well.

**Comment by SandakovMM** [comment]
I added support for the /etc/yum.repo.d/MariaDB10.repo file in issue #252, so conversion with this file should now work correctly.
