### ISSUE TITLE
centos2alma Upgrade failed

### ISSUE THREAD

**Issue by msiegling** [plesk/centos2alma#296]
The dist-ugrade process has failed. See the /var/log/plesk/centos2alma.log file for more information.
The last 100 lines of the file are shown above.
For assistance, call 'centos2alma --prepare-feedback' and follow the instructions.
[centos2alma_feedback.zip](https://github.com/user-attachments/files/16081066/centos2alma_feedback.zip)

**Comment by SandakovMM** [comment]
It seems the conversion failed during the installation of dnf and pciutils, which are dependencies for leapp. This is likely due to the end of life of CentOS 7. Since the old CentOS 7 repositories are no longer available, dnf cannot be installed.
I believe you can resolve the issue by switching to the vault repositories. For example, the base repository can be found at `http://vault.centos.org/centos/$releasever/os/$basearch`.

I will add a pre-checker for the problem

**Comment by SandakovMM** [comment]
I've added a pre-checker in #299
