### ISSUE TITLE
Cronjob hourly error (/etc/cron.daily/01-awp_daily)

### ISSUE THREAD

**Issue by christiaanbruijnes** [plesk/centos2alma#385]
I am receiving the following errors in the mail after the upgrade, anyone else who had this problem or solved this? The upgrade self was a success after some struggling. After the upgrade the Almalinux was stuck and really slow, there was something wrong with httpd which fixed itself after some minutes, really strange though.

```
/etc/cron.daily/01-awp_daily:

/etc/cron.daily/01-awp_daily: line 2: /var/awp/etc/config: No such file or directory
/etc/cron.daily/aum_nightly.sh:

/etc/cron.daily/aum_nightly.sh: line 2: /var/awp/etc/config: No such file or directory
```
I wonder if this is a problem and how this could be solved, it sending me a mail every hour.

**Comment by farisc1** [comment]
Did you have the Atomic mod_security ruleset enabled before you upgraded?
Even if you didn't have it enabled currently, might you have done so previously?

I suggest this purely because awp and aum are potentially related to ruleset management for the Atomic ruleset, but I'm unfamiliar with the way Plesk implements updates which is different to the "native" way, so maybe I'm totally wrong..

I don't understand why you are getting the emails hourly though, as these should run daily not hourly.

**Comment by SandakovMM** [comment]
The issue seems to be related to the atomic ruleset. If you're not using it, it should be safe to delete the cron job.

It's unusual that you don't have atomic installer configurations after the conversion. There might be a missing aum package for some reason. Could you please provide a feedback archive?
